# Generated by Django 4.0.3 on 2022-03-09 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('numbering', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('img', models.ImageField(height_field=300, upload_to='article', width_field=200)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='menuBlog.section')),
            ],
        ),
    ]
