# Generated by Django 4.0.3 on 2022-03-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuBlog', '0002_dish_price_alter_dish_img_alter_dish_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='gram',
            field=models.IntegerField(default=250),
            preserve_default=False,
        ),
    ]
